version: "3"
services: 
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    image: "microsoft/mssql-server-linux"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y" 