// <auto-generated />
using campanhabrinquedo.domain.Entities;
using campanhabrinquedo.repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace campanhabrinquedo.repositorio.Migrations
{
    [DbContext(typeof(CampanhaBrinquedoContext))]
    [Migration("20170927032622_Refactor")]
    partial class Refactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Campanha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("Descricao");

                    b.Property<int>("QtdeCriancas");

                    b.HasKey("Id");

                    b.ToTable("Campanha");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Comunidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Comunidade");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Crianca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ComunidadeId");

                    b.Property<bool>("Especial");

                    b.Property<string>("Idade");

                    b.Property<bool>("Impresso");

                    b.Property<string>("Nome");

                    b.Property<Guid?>("ResponsavelId");

                    b.Property<int>("Sexo");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadeId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Crianca");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Padrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<Guid?>("ComunidadeId");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.HasIndex("ComunidadeId");

                    b.ToTable("Padrinho");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<string>("RG");

                    b.HasKey("Id");

                    b.ToTable("Responsavel");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Crianca", b =>
                {
                    b.HasOne("campanhabrinquedo.domain.Entities.Comunidade", "Comunidade")
                        .WithMany()
                        .HasForeignKey("ComunidadeId");

                    b.HasOne("campanhabrinquedo.domain.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");
                });

            modelBuilder.Entity("campanhabrinquedo.domain.Entities.Padrinho", b =>
                {
                    b.HasOne("campanhabrinquedo.domain.Entities.Comunidade", "Comunidade")
                        .WithMany()
                        .HasForeignKey("ComunidadeId");
                });
#pragma warning restore 612, 618
        }
    }
}
